[build]
  publish = "build"  # Adjust this path to your build output directory if different
  command = "npm run build"  # Adjust this command to your build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
